#! /bin/bash

# Check for identical output between a new set of output and
# output generated by Will Kleiber
#
# arguments:
# dateStr : 8 digit date to compare, yyyymmdd

dateStr=$1

newDir=/pl/active/SierraBighorn/downscaledv3_test
origDir=/pl/active/SierraBighorn/downscaledv3

# Actual output file
newFile=${newDir}/downscaled/3e+05/SSN.downscaled.${dateStr}.v3.3e+05.tif
origFile=${origDir}/downscaled/3e+05.test/SSN.downscaled.${dateStr}.v3.tif
diff -s $newFile $origFile

# prob.btwn file
newFile=${newDir}/prob.btwn/3e+05/SSN.downscaled.prob.0.100.${dateStr}.v3.3e+05.tif
origFile=${origDir}/prob.btwn/3e+05/SSN.downscaled.prob.0.100.${dateStr}.v3.tif
diff -s $newFile $origFile

# prob.hundred file
newFile=${newDir}/prob.hundred/3e+05/SSN.downscaled.prob.100.${dateStr}.v3.3e+05.tif
origFile=${origDir}/prob.hundred/3e+05/SSN.downscaled.prob.100.${dateStr}.v3.tif
diff -s $newFile $origFile

# regression file
newFile=${newDir}/regression/3e+05/SSN.downscaled.regression.${dateStr}.v3.3e+05.tif
origFile=${origDir}/regression/3e+05/SSN.downscaled.regression.${dateStr}.v3.tif
diff -s $newFile $origFile
