#! /bin/bash

# Check for identical output between a new set of output and
# output generated by Shalini 
#
# arguments:
# dateStr : 8 digit date to compare, yyyymmdd

dateStr=$1

newDir=/pl/active/SierraBighorn/downscaledv4_test
origDir=/pl/active/SierraBighorn/downscaledv4

#FIXME: Shalini needs to rename her files to v4, for now, comparing to v3 filenames:

# Actual output file
newFile=${newDir}/downscaled/3e+05/SSN.downscaled.${dateStr}.v4.3e+05.tif
origFile=${origDir}/downscaled/SSN.downscaled.${dateStr}.v3.tif
diff -s $newFile $origFile

# prob.btwn file
newFile=${newDir}/prob.btwn/3e+05/SSN.downscaled.prob.0.100.${dateStr}.v4.3e+05.tif
origFile=${origDir}/prob.btwn/SSN.downscaled.${dateStr}.v3.tif
#origFile=${origDir}/prob.btwn/SSN.downscaled.prob.0.100.${dateStr}.v3.tif
diff -s $newFile $origFile

# prob.hundred file
newFile=${newDir}/prob.hundred/3e+05/SSN.downscaled.prob.100.${dateStr}.v4.3e+05.tif
origFile=${origDir}/prob.hundred/SSN.downscaled.${dateStr}.v3.tif
#origFile=${origDir}/prob.hundred/SSN.downscaled.prob.100.${dateStr}.v3.tif
diff -s $newFile $origFile

# regression file
newFile=${newDir}/regression/3e+05/SSN.downscaled.regression.${dateStr}.v4.3e+05.tif
origFile=${origDir}/regression/SSN.downscaled.${dateStr}.v3.tif
#origFile=${origDir}/regression/SSN.downscaled.regression.${dateStr}.v3.tif
diff -s $newFile $origFile
